steps:
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/dipayan-trials/dipayan-tests/test-image-0.0.1', '--build-arg=JAR_FILE=target/myproject-0.0.1-SNAPSHOT.jar', '.']
images: ['europe-west2-docker.pkg.dev/dipayan-trials/dipayan-tests/test-image-0.0.1']
