apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: push-workflow
  labels:
    app: hello-world-spring-boot-master
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: hello-world-spring-boot-master
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-spring-boot-master
    spec:
      containers:
        - image: {{.Values.image.repository}}
          name: app
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources: { }
          ports:
            - containerPort: 8080
status: { }
